### ISSUE TITLE
Allow multiple tutorial formats

### ISSUE THREAD

**Issue by ooloth** [ooloth/gatsbytutorials.com#19]
## Summary

Allow tutorials to include multiple formats (e.g. "text" and "video") instead of just one.

## Motivation

- Sometimes, contributors want to categorize a tutorial's format as both "text" and "video" (e.g. for a blog post that include embedded video content)
- Since the `format` property is currently a `string`, contributors need to pick just one primary format, but this is sometimes less accurate than listing multiple formats
- I missed this issue on a tutorial submission that listed the format as "text, video", so the directory now includes a "text, video" format, which is clearly a bug
- The best solution (both logically and practically) is simply to drop the one format restriction

## Approach

1. Rename all of the `format` fields in [`src/data/tutorials.yml`](https://github.com/ooloth/gatsbytutorials.com/blob/master/src/data/tutorials.yml) to `formats` (i.e. add an "s")
2. Convert all of the `formats` values to an `array` of `strings` (rather than a single `string`)
3. Update the [construction of the formats list](https://github.com/ooloth/gatsbytutorials.com/blob/master/src/pages/index.js#L10-L12) to work with the new `array` format
4. Update [the logic that assigns an emoji](https://github.com/ooloth/gatsbytutorials.com/blob/master/src/components/Tutorial.js#L27-L33) to each tutorial to one of the following:
a. Show multiple emoji (accurate, but will make the layout inconsistent)?
b. Choose a single emoji based on an emoji hierarchy (e.g. 📺 > 🎧 > ✍️)?
c. Other logic? I'm open to suggestions here...
5. Update `README.md` instructions

### Old syntax ❌ 
```yaml
format: video
```

### New syntax ✅ 
```yaml
formats: 
- video
```

**Comment by JesseSingleton** [comment]
@ooloth I can take a look at this.

On the logic emoji I can experiment with a. see how that looks. We could also just take the first format that the user adds in the array and only display that; then the user can decide which emoji they'd like displayed.

**Comment by JesseSingleton** [comment]
I don't think the first option looks terrible to be honest.

![image](https://user-images.githubusercontent.com/17176370/63424051-7ea2f480-c405-11e9-8a8f-fada3116bccd.png)

Let me know what you think.

**Comment by ooloth** [comment]
@JesseSingleton Awesome! Thanks for tackling this.

I think (a) looks good, too (show multiple emoji if there are multiple formats). Let me know if you run into any issues.
